[package]
name = "iec61131-std"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dev-dependencies]
inkwell = {git = "https://github.com/TheDan64/inkwell", branch="master", features=["llvm12-0"] }
rusty = {git = "https://github.com/PLC-lang/rusty", branch="master" } 

[lib]
crate-type = ["staticlib", "cdylib", "lib"]

