[package]
name = "iec61131-std"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dev-dependencies]
rusty = {git = "https://github.com/PLC-lang/rusty", branch="master" } 
